"""
Django settings for barmichev project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(env_file=os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DJANGO_DEBUG', default=False)

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '.barmichev.ru',
    '.barmichev.com',
    '194.67.105.231'
]

INTERNAL_IPS = []
if DEBUG:
    INTERNAL_IPS += ['127.0.0.1']

# CORS settings
# CORS_ALLOW_CREDENTIALS = True

if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOWED_ORIGINS = []
    for host in ALLOWED_HOSTS:
        domain = host[1:] if host.startswith('.') else host
        CORS_ALLOWED_ORIGINS.append(f'https://{domain}')

# Application definition
ADMIN_ENABLED = False

INSTALLED_APPS = [
    'users',
    'knowledge',
    'home',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'wagtail.contrib.forms',
    'wagtail.contrib.redirects',
    'wagtail.embeds',
    'wagtail.sites',
    'wagtail.users',
    'wagtail.snippets',
    'wagtail.documents',
    'wagtail.images',
    'wagtail.search',
    'wagtail.admin',
    'wagtail',
    'modelcluster',
    'taggit',
    'wagtailcodeblock'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'wagtail.contrib.redirects.middleware.RedirectMiddleware',
]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

AUTH_USER_MODEL = 'users.User'

ROOT_URLCONF = 'barmichev.urls'

TEMPLATES_DIR = os.path.join(BASE_DIR, 'templates')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'barmichev.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.postgresql',
        'ENGINE': 'barmichev.tools.db_engine',
        'NAME': env('DB_NAME'),
        'USER': env('POSTGRES_USER'),
        'PASSWORD': env('POSTGRES_PASSWORD'),
        'HOST': env('DB_HOST', default='127.0.0.1'),
        'PORT': env('DB_PORT', default='5432'),
    }
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME':
            'django.contrib.auth.password_validation.'
            'UserAttributeSimilarityValidator',
    },
    {
        'NAME':
            'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME':
            'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME':
            'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru'
TIME_ZONE = 'Europe/Moscow'
USE_I18N = True
USE_TZ = True
DATE_FORMAT = 'd.m.Y'
DATETIME_FORMAT = 'd.m.Y H:i'
FIRST_DAY_OF_WEEK = 1

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATICFILES_DIRS = [
    BASE_DIR / 'staticshare/backend/build',
    BASE_DIR / 'staticshare/frontend/build',
    # BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'
STATIC_URL = '/staticfiles/'

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

# Logging
LOG_DIR = BASE_DIR / 'logs'
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)

LOG_BASE_FILE = LOG_DIR / 'maintains.log'
LOG_KNOWLEDGE_FILE = LOG_DIR / 'knowledge.log'
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {name} {message}',
            'datefmt': '%H:%M:%S',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'datefmt': '%H:%M:%S',
            'style': '{',
        }
    },
    'handlers': {
        'base_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_BASE_FILE,
            'maxBytes': 1024 * 1024 * 5,
            'backupCount': 1,
            'formatter': 'verbose',
            'encoding': 'utf-8'
        },
        'knowledge_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_KNOWLEDGE_FILE,
            'maxBytes': 1024 * 1024 * 5,
            'backupCount': 1,
            'formatter': 'verbose',
            'encoding': 'utf-8'
        }
    },
    'loggers': {
        'django': {
            'handlers': ['base_file'],
            'level': 'INFO',
            'propagate': True,
        },
        'barmichev': {
            'handlers': ['base_file'],
            'level': 'INFO',
            'propagate': True,
        },
        'knowledge': {
            'handlers': ['knowledge_file'],
            'level': 'INFO',
            'propagate': True,
        }
    }
}

# SETTINGS BY WAGTAIL.
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10_000
WAGTAILIMAGES_MAX_UPLOAD_SIZE = 20 * 1024 * 1024

WAGTAIL_SITE_NAME = 'Barmichev.ru'
WAGTAILADMIN_BASE_URL = 'https://barmichev.ru'
WAGTAILDOCS_EXTENSIONS = ['docx', 'odt', 'pdf', 'pptx', 'rtf', 'txt', 'xlsx']
WAGTAILEMBEDS_RESPONSIVE_HTML = True

# WAGTAILADMIN_RICH_TEXT_EDITORS = {
#     'default': {
#         'WIDGET': 'wagtail.admin.rich_text.DraftailRichTextArea',
#         'OPTIONS': {
#             'features': ['h2', 'bold', 'italic', 'link', 'document-link']
#         }
#     },
#     'secondary': {
#         'WIDGET': 'some.external.RichTextEditor',
#     }
# }

WAGTAILADMIN_RICH_TEXT_EDITORS = {
    'default': {
        'WIDGET': 'wagtail.admin.rich_text.DraftailRichTextArea',
        'OPTIONS': {
            'features': [
                'h1', 'h2', 'h3', 'h4', 'h5', 'h6',  # Заголовки
                # Форматирование текста
                'bold', 'italic', 'underline', 'strikethrough',
                'code', 'blockquote',  # Код и цитаты
                'ol', 'ul', 'li',  # Списки
                'link', 'document-link', 'image', 'embed',  # Медиа
                'hr',  # Разделитель
                'superscript', 'subscript',  # Верхний/нижний индекс
            ]
        }
    },
    'full': {
        'WIDGET': 'wagtail.admin.rich_text.DraftailRichTextArea',
        'OPTIONS': {
            'features': [
                'h1', 'h2', 'h3', 'h4', 'h5', 'h6',
                'bold', 'italic', 'underline', 'strikethrough',
                'code', 'blockquote',
                'ol', 'ul', 'li',
                'link', 'document-link', 'image', 'embed',
                'hr',
                'superscript', 'subscript',
            ]
        }
    }
}

WAGTAIL_CODE_BLOCK_LANGUAGES = (
    ('bash', 'Bash/Shell'),
    ('css', 'CSS'),
    ('html', 'HTML'),
    ('javascript', 'Javascript'),
    ('json', 'JSON'),
    ('python', 'Python'),
    ('yaml', 'YAML'),
    ('rust', 'Rust'),
    ('c', 'C'),
)

# Disable commenting
WAGTAILADMIN_COMMENTS_ENABLED = False
# Адреса страниц могут содержать любые символы, включая нелатинские.
WAGTAIL_ALLOW_UNICODE_SLUGS = False

WAGTAILADMIN_PERMITTED_LANGUAGES = [('en', 'English'),
                                    ('ru', 'Русский')]

# Сделаем теги нечувствительными к регистру.
TAGGIT_CASE_INSENSITIVE = False
WAGTAIL_TAG_LIMIT = 10  # Ограничение на число тегов.
