# Generated by Django 5.2.8 on 2025-11-21 20:27

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_articlepagegalleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0), ('code', 3), ('image', 4), ('quote', 5)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'underline', 'code', 'blockquote', 'ol', 'ul', 'link', 'image', 'hr'], 'label': 'Текст'}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('bash', 'Bash/Shell'), ('css', 'CSS'), ('html', 'HTML'), ('javascript', 'Javascript'), ('json', 'JSON'), ('python', 'Python'), ('yaml', 'YAML'), ('rust', 'Rust'), ('c', 'C')], 'help_text': 'Coding language', 'identifier': 'language', 'label': 'Language'}), 2: ('wagtail.blocks.TextBlock', (), {'identifier': 'code', 'label': 'Code'}), 3: ('wagtail.blocks.StructBlock', [[('language', 1), ('code', 2)]], {'label': 'Блок кода'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение'}), 5: ('wagtail.blocks.BlockQuoteBlock', (), {'label': 'Цитата'})}),
        ),
    ]
